export const placementdata = [
  {
    id: 1,
    name: "Aarav Patel",
    role: "Frontend Developers",
    company: "Tata Consultancy Services (TCS)",
    img: "https://xsgames.co/randomusers/assets/avatars/male/1.jpg",
  },
  {
    id: 2,
    name: "Priya Sharma",
    role: "UI/UX Designer",
    company: "Infosys",
    img: "https://xsgames.co/randomusers/assets/avatars/female/2.jpg",
  },
  {
    id: 3,
    name: "Rahul Verma",
    role: "Full Stack Developer",
    company: "Wipro",
    img: "https://xsgames.co/randomusers/assets/avatars/male/3.jpg",
  },
  {
    id: 4,
    name: "Neha Gupta",
    role: "Data Analyst",
    company: "Accenture",
    img: "https://xsgames.co/randomusers/assets/avatars/female/4.jpg",
  },
  {
    id: 5,
    name: "Vikram Reddy",
    role: "Backend Engineer",
    company: "HCL Technologies",
    img: "https://xsgames.co/randomusers/assets/avatars/male/5.jpg",
  },
  {
    id: 6,
    name: "Meera Iyer",
    role: "Digital Marketing Executive",
    company: "Zoho Corporation",
    img: "https://xsgames.co/randomusers/assets/avatars/female/6.jpg",
  },
  {
    id: 7,
    name: "Arjun Nair",
    role: "Software Developer",
    company: "IBM",
    img: "https://xsgames.co/randomusers/assets/avatars/male/7.jpg",
  },
  {
    id: 8,
    name: "Kavya Menon",
    role: "Cloud Engineer",
    company: "Amazon Web Services (AWS)",
    img: "https://xsgames.co/randomusers/assets/avatars/female/8.jpg",
  },
  {
    id: 9,
    name: "Rohan Das",
    role: "React Developer",
    company: "Capgemini",
    img: "https://xsgames.co/randomusers/assets/avatars/male/9.jpg",
  },
  {
    id: 10,
    name: "Sneha Kulkarni",
    role: "Business Analyst",
    company: "Deloitte",
    img: "https://xsgames.co/randomusers/assets/avatars/female/10.jpg",
  },
  {
    id: 11,
    name: "Ankit Singh",
    role: "Java Developer",
    company: "Tech Mahindra",
    img: "https://xsgames.co/randomusers/assets/avatars/male/11.jpg",
  },
  {
    id: 12,
    name: "Divya Ramesh",
    role: "Data Scientist",
    company: "Google",
    img: "https://xsgames.co/randomusers/assets/avatars/female/12.jpg",
  },
  {
    id: 13,
    name: "Harish Kumar",
    role: "Python Developer",
    company: "Microsoft",
    img: "https://xsgames.co/randomusers/assets/avatars/male/13.jpg",
  },
  {
    id: 14,
    name: "Nisha Jain",
    role: "Mobile App Developer",
    company: "Cognizant",
    img: "https://xsgames.co/randomusers/assets/avatars/female/14.jpg",
  },
  {
    id: 15,
    name: "Karan Mehta",
    role: "MERN Stack Developer",
    company: "Accolite Digital",
    img: "https://xsgames.co/randomusers/assets/avatars/male/15.jpg",
  },
  {
    id: 16,
    name: "Ritika Singh",
    role: "SEO Specialist",
    company: "Freshworks",
    img: "https://xsgames.co/randomusers/assets/avatars/female/16.jpg",
  },
  {
    id: 17,
    name: "Aditya Rao",
    role: "AI Engineer",
    company: "NVIDIA",
    img: "https://xsgames.co/randomusers/assets/avatars/male/17.jpg",
  },
  {
    id: 18,
    name: "Pooja Patel",
    role: "Graphic Designer",
    company: "Adobe",
    img: "https://xsgames.co/randomusers/assets/avatars/female/18.jpg",
  },
  {
    id: 19,
    name: "Sanjay Kumar",
    role: "Cyber Security Analyst",
    company: "Cisco",
    img: "https://xsgames.co/randomusers/assets/avatars/male/19.jpg",
  },
  {
    id: 20,
    name: "Aishwarya Raj",
    role: "Product Manager",
    company: "Google",
    img: "https://xsgames.co/randomusers/assets/avatars/female/20.jpg",
  },
];
